### ISSUE TITLE
Unbundled bundle since sourcemap doesn't help

### ISSUE THREAD

**Issue by janat08** [asimbera/esbuild-worker-starter#1]
Considering the sourcemaps aren't used, is it possible to use es modules so that you don't get a line 1000 throwing error, so that you can tell what the problem is, if not minifying.

**Comment by asimbera** [comment]
As I'm aware of, wrangler does not support source map, so I didn't add source map generation in the initial version.
For better development experience I've added [`miniflare`](https://miniflare.dev/) which natively supports source maps, debug protocols and many more features.

As for the es module support, it requires some change in source structure and build flags (in case of esbuild it is globbing which requires external plugins or custom build script) which I'll add pretty soon.
